### ISSUE TITLE
Porting to Godot 4

### ISSUE THREAD

**Issue by fire** [CaptainProton42/GodotHoloPlay#4]
Trying to develop a plan for Godot 4.

**Comment by CaptainProton42** [comment]
Heyo, just to keep track of this here as well:

https://github.com/CaptainProton42/GodotHoloPlayNative/commit/9cf76cd3592b5ceb036ccd29264eea5f0826851d moved a lot of the rendering that was previsously done in OpenGL using framebuffers to the Godot VisualServer (using Viewports and TextureRects).

This means that the main things that are being done "outside" of Godot rendering-wise are creating a separate window (using GLFW) and compiling and running the ligthfield shader from HoloPlayCore (using OpenGL and some native Windows calls such as wglMakeCurrent to draw to the window).

I haven't looked at Godot 4 yet that closely but I've heard that it'll have support for multiple windows so this part could be moved to Godot as well. Compiling the lightfield shader in-engine would require support for GLSL shaders in Godot 4 though.

**Comment by fire** [comment]
I have verified that this demo works in Godot Engine https://github.com/fire/looking-glass/.

It's a shader that converts 45 images to Looking Glass Format. 

I wasn't able to solve the 45 images generation problem. It's blocking me.

**Comment by CaptainProton42** [comment]
https://github.com/fire/looking-glass/blob/master/godot_demo/looking_glass.gdshader

Is this the shader file? That's really cool. How did you figure the shader out?

I'm a bit afraid of including a plain text lightfield shader due to licensing which means I hope to be able to import the GLSL code from the DLL in Godot 4.

Regarding generating the 45 views: I used the VisualServer to create the 45 cameras (or less for most settings since 45 views are pretty heavy) and viewports and let the engine do the rest. You could then use the Viewport textures in your shader. PROJECTION_FRUSTUM works really well for the cameras as it doesn't distort the focal plane.

**Comment by fire** [comment]
It was derived from https://github.com/fire/looking-glass/blob/master/linquilt2native.py

**Comment by fire** [comment]
Can you provide some sample code that does this and outputs to my quilt inputs? 

I have trouble converting the 45 images to a ImageArray2d, so being able to match my inputs is really helpful.

**Comment by fire** [comment]
The second bit usb access to:

> get_calibration_from_eeprom.py: Get the display calibration values (in the form of a JSON string) from a Looking Glass.

**Comment by CaptainProton42** [comment]
> Can you provide some sample code that does this and outputs to my quilt inputs?
> 
> I have trouble converting the 45 images to a ImageArray2d, so being able to match my inputs is really helpful.

This is the code in the GDNative library that creates the cameras/viewports:

https://github.com/CaptainProton42/GodotHoloPlayNative/blob/1b1de0d24cc414e7409779a9621313349ff2ce86/src/godot_holoplay/HoloPlayVolume.cpp#L476-L508

I'll try to outline it a bit: Using `VisualServer`, I create up to 45 cameras, viewports and texture rects. Each camera renders a view to a viewport whose texture is displayed on a texture rect. By adding all texture rects in a grid to a parent canvas item I essentially create the quilt where each view is updated by one camera/viewport. The parent canvas item is also attached to a viewport. The texture of this root viewport will be the quilt you want.

There is also the `update_cameras()` function which sets the projections for all cameras:

https://github.com/CaptainProton42/GodotHoloPlayNative/blob/1b1de0d24cc414e7409779a9621313349ff2ce86/src/godot_holoplay/HoloPlayVolume.cpp#L513-L543

This article was really helpful for getting the correct projections: https://docs.lookingglassfactory.com/keyconcepts/camera

**Comment by CaptainProton42** [comment]
> The second part is usb access to:
> 
> > get_calibration_from_eeprom.py: Get the display calibration values (in the form of a JSON string) from a Looking Glass.

I think the easiest solution to this is just writing a wrapper for the HoloPlayCore SDK in GDNative. I'll probably try to do that this week as first step of getting it to run in Godot 4.

**Comment by CaptainProton42** [comment]
Godot 4 development has been moved to https://github.com/CaptainProton42/GodotHoloPlayExtension using the new extension system.
